### ISSUE TITLE
RoseStack doesn't work on 1.19 Paper Server

### ISSUE THREAD

**Issue by DevCyntrix** [Rosewood-Development/RoseStacker#57]
Hi,

I tried to use RoseStacker on my 1.19 Paper Server, but it doesn't work perfectly. 
The plugin through an exception constantly. I use the newest 1.19 build of Paper and the newest RoseStacker version.

[Sun 14:07:59 ERROR Minecraft] Could not pass event CreatureSpawnEvent to RoseStacker v1.4.13
java.lang.NoSuchMethodError: 'double net.minecraft.world.entity.EntityLiving.df()'
    at RoseStacker-1.4.13.jar//dev.rosewood.rosestacker.nms.v1_19_R1.NMSHandlerImpl.hasLineOfSight(NMSHandlerImpl.java:434)
    at RoseStacker-1.4.13.jar//dev.rosewood.rosestacker.nms.NMSHandler.hasLineOfSight(NMSHandler.java:188)
    at RoseStacker-1.4.13.jar//dev.rosewood.rosestacker.utils.EntityUtils.hasLineOfSight(EntityUtils.java:68)
    at RoseStacker-1.4.13.jar//dev.rosewood.rosestacker.stack.StackingThread.tryStackEntity(StackingThread.java:904)
    at RoseStacker-1.4.13.jar//dev.rosewood.rosestacker.stack.StackingThread.createEntityStack(StackingThread.java:534)
    at RoseStacker-1.4.13.jar//dev.rosewood.rosestacker.manager.StackManager.createEntityStack(StackManager.java:268)
    at RoseStacker-1.4.13.jar//dev.rosewood.rosestacker.listener.EntityListener.lambda$onCreatureSpawn$0(EntityListener.java:126)
at RoseStacker-1.4.13.jar//dev.rosewood.rosestacker.listener.EntityListener.onCreatureSpawn(EntityListener.java:135)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor256.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
    at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:739)
    at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:644)
    at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1444)
    at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1352)
    at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassen

**Comment by Esophose** [comment]
RoseStacker v1.4.13 does not support 1.19, only 1.19.1 and 1.19.2. You will need to use v1.4.12 until you're able to update your server
